// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyhmduSAzXCE_8UFNgKhp7Lv17LorXu5Y',
    appId: '1:1023394063170:web:624bcc8f728d82616d1edb',
    messagingSenderId: '1023394063170',
    projectId: 'ysf-app-bbf97',
    authDomain: 'ysf-app-bbf97.firebaseapp.com',
    storageBucket: 'ysf-app-bbf97.appspot.com',
    measurementId: 'G-5GVEPCTH3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLfjacoTrr10WZ849wffntifIJfQivkc',
    appId: '1:1023394063170:android:c51298a1491b83966d1edb',
    messagingSenderId: '1023394063170',
    projectId: 'ysf-app-bbf97',
    storageBucket: 'ysf-app-bbf97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXRVuzdYAMEVdEy3Jp66HH2oLHDsXymw',
    appId: '1:1023394063170:ios:75fd75ca7fa327dc6d1edb',
    messagingSenderId: '1023394063170',
    projectId: 'ysf-app-bbf97',
    storageBucket: 'ysf-app-bbf97.appspot.com',
    iosBundleId: 'com.example.ysf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUXRVuzdYAMEVdEy3Jp66HH2oLHDsXymw',
    appId: '1:1023394063170:ios:75fd75ca7fa327dc6d1edb',
    messagingSenderId: '1023394063170',
    projectId: 'ysf-app-bbf97',
    storageBucket: 'ysf-app-bbf97.appspot.com',
    iosBundleId: 'com.example.ysf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyhmduSAzXCE_8UFNgKhp7Lv17LorXu5Y',
    appId: '1:1023394063170:web:011d4be7681f195f6d1edb',
    messagingSenderId: '1023394063170',
    projectId: 'ysf-app-bbf97',
    authDomain: 'ysf-app-bbf97.firebaseapp.com',
    storageBucket: 'ysf-app-bbf97.appspot.com',
    measurementId: 'G-HSD7YF6FZF',
  );
}
